Hotfix/single tab bug
dataiku/solutions-contrib pull request #46
Opened 2023-03-16 18:28 UTC by levkz

Using tabs feature with one tab was breaking it
### Input:
![image](https://user-images.githubusercontent.com/36790863/225718140-b6af4aa5-b6da-4d77-84d8-17d040cf5a7c.png)

### Output:
![image](https://user-images.githubusercontent.com/36790863/225718191-771d8be5-61f4-42f2-a323-6f17610da3b4.png)

2023-03-17 11:24 UTC, HenriChabert requested changes
Just two debug messages, otherwise, tested and everything works fine!

2023-03-17 11:24 UTC, HenriChabert commented on commons/_shared/bs-lib-components/ui/src/components/layout/BsLayoutDefault.vue
> +            console.log("this.defaultTabUsed: ", this.defaultTabUsed);
Debug msg

2023-03-17 11:24 UTC, HenriChabert commented on commons/_shared/bs-lib-components/ui/src/components/layout/BsTab.vue
> +        console.log("mounted a tab: ", this.tab);
Debug msg

2023-03-27 15:02 UTC, levkz commented on commons/_shared/bs-lib-components/ui/src/components/layout/BsLayoutDefault.vue
> +            console.log("this.defaultTabUsed: ", this.defaultTabUsed);
changed in 9602ae0

2023-03-27 15:04 UTC, HenriChabert approved these changes

2023-03-27 15:16 UTC, merged