Feature/dfc sc 138098 align with table design
dataiku/solutions-contrib pull request #53
Opened 2023-05-29 15:21 UTC by helaot

- fix table header

- fix table search bar

- fix table columns

- fix table rows

2023-06-01 08:50 UTC, levkz requested changes
Good job on the design!

There are a few comments that need to be tended to:
- the sorting logic fails, I've sent you the video in Slack and left a comment.
- virtual scroll is broken, probably some css you've removed, we used parent element height to set the max height of the table, here is quasar link to [virtual scroll](https://quasar.dev/vue-components/table#virtual-scrolling)
- if you test the table on DSS Dataset *(:dss-table-name prop)*  the headers row won't be displayed for some reason.
- There is no way to paginate the DSS Dataset (unless you've implemented infinite scroll).

2023-06-01 08:50 UTC, levkz commented on commons/_shared/bs-lib-components/ui/src/components/table/BsTableColHeader.vue
>              if (this.sortable && this.sort) this.sort(this.col);
- There are three states - unsorted, sorted descending, sorted ascending, you have to account for that in your boolean flag `sortDesc`.
- `sortColIcon` can be a computed property.

2023-06-01 08:50 UTC, levkz commented on commons/_shared/bs-lib-components/ui/src/components/table/BsTableColHeader.vue
>              if (this.sortable && this.sort) this.sort(this.col);
<img width="1544" alt="image" src="https://github.com/dataiku/solutions-contrib/assets/36790863/d7176e20-27d9-4ff2-9364-dca554e73e72">

2023-06-01 09:39 UTC, helaot commented on commons/_shared/bs-lib-components/ui/src/components/table/BSTableHeader.vue
> +        <q-th auto-width />
- virtual scroll is broken : how can I test it ?
- I wasn't able to test with (:dss-table-name prop) in the project other than the error part as I was getting errors. How did you manage to test it ? 
- There is no way to paginate the DSS Dataset (unless you've implemented infinite scroll). : what do you mean ?

2023-06-01 12:23 UTC, helaot commented on commons/_shared/bs-lib-components/ui/src/components/table/BSTableHeader.vue
> +        <q-th auto-width />
Update : I managed to test with dss-table-name the virtual scroll didn't seem to be working before my changes

2023-06-06 10:57 UTC, levkz approved these changes
LGTM!

2023-06-06 13:29 UTC, merged